### ISSUE TITLE
500 error when trying to make and download PDF

### ISSUE THREAD

**Issue by blackstarek** [tasmanianfox/MpdfPortBundle#16]
Hey, I'm gettin 500 when running this code:

        $html = $this->renderView('AppBundle:LunchMenu:menu.html.twig',$params);
        $mpdfService = $this->get('tfox.mpdfport');

        return new Response($mpdfService->generatePdfResponse($html),
            array(
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => 'attachment; filename="poledni_menu.pdf"'
            )
        );

Do you know, what could be wrong? Thank you

UPDATE: In dev enviroment i get You have requested a non-existent service "tfox.mpdfport".

**Comment by marcel-burkhard** [comment]
Make sure you added the bundle to your AppKernel.php

**Comment by tasmanianfox** [comment]
Sorry for my late response, I really missed this issue. I agree with @marcel-burkhard , please check if you added the bundle to AppKernel.php. It is strange that Symfony cannot find the service in DEV environment. Do you still have this issue?

In addition, you should not use an output of ```generatePdfResponse``` method as constructor for Response class, because method ```generatePdfResponse``` returns a response itself, so your code puts an instance of Response into another instance of Response. If you would like to create an instance of Response manually, you should use ```generatePdf``` method instead:

```
    $html = $this->renderView('AppBundle:LunchMenu:menu.html.twig',$params);
    $mpdfService = $this->get('tfox.mpdfport');


    return new Response($mpdfService->generatePdf($html),
        array(
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'attachment; filename="poledni_menu.pdf"'
        )
    );
```
