### ISSUE TITLE
Error when generating a pdfwith symfony 2.6 version

### ISSUE THREAD

**Issue by selossevianney** [tasmanianfox/MpdfPortBundle#18]
Hello,

when I try to generate a pdf, I have this error : 
<p>Error message detected - PDF file generation aborted.</p>The Symfony\Component\Security\Core\SecurityContext class is deprecated since version 2.6 and will be removed in 3.0. Use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage or Symfony\Component\Security\Core\Authorization\AuthorizationChecker instead.
<br />File: /myapp/vendor/symfony/symfony/src/Symfony/Component/Security/Core/SecurityContext.php
<br />Line: 14
<br />

It seems to be a depreciation warning message, so, why mpdf take it as an error message ? The thing is, even if I resolve this problem by commenting the line that cause trouble in the Symfony file concerned, I have the same type of message in an other file. I will not modify every Symfony files, so, I commented the responsible line in mpdf.php (l. 8185) and surprise : the pdf was generated correctly without one single error. 

My question is : how do I can get rid of this error without modifying anything in your code, or in symfony components code?

**Comment by tasmanianfox** [comment]
Hi.

I seriously doubt that MpdfPortBundle could cause such kind of warning messages, because it doesn't use Symfony Security component. I also don't recommend you to modify any vendor files, because you'll have problems with updates in the future.

I can suggest you just two options:
- Roll back to Symfony version 2.5 or earlier
- Replace injection of ```security.context``` service with alternatives that were introduced in Symfony v. 2.6 as described here http://symfony.com/blog/new-in-symfony-2-6-security-component-improvements 

As you wrote that modifying of code is undesirable, the only first option remains.

**Comment by tasmanianfox** [comment]
@selossevianney 
May be this information would be also useful for you.
Today I had the same error when I tried to create a directory using Symfony Filesystem component:
```
The Symfony\Component\Security\Core\SecurityContext class is deprecated since version 2.6 and will be removed in 3.0. Use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage or Symfony\Component\Security\Core\Authorization\AuthorizationChecker instead.
```
An exception was raised in the code below:
```
            if (true !== @mkdir($dir, $mode, true)) {
                $error = error_get_last();
                if (!is_dir($dir)) {
                    // The directory was not created by a concurrent process. Let's throw an exception with a developer friendly error message if we have one
                    if ($error) {
                        throw new IOException(sprintf('Failed to create "%s": %s.', $dir, $error['message']), 0, null, $dir);
                    }
                    throw new IOException(sprintf('Failed to create "%s"', $dir), 0, null, $dir);
                }
            }
```
This code is taken from Filesystem component. After I removed "@" near ```mkdir``` function call, the actual error ("Permission denied") was displayed. The idea is that the actual problem in your case might be not related to deprecated SecurityContext service, because function ```error_get_last()``` in some reason doesn't return the last error.

**Comment by selossevianney** [comment]
@tasmanianfox 
Hi , thanks for your quick reply.

I can't rollback to 2.5 because it's not my personal project so I will not do that. I know that it is not the best thing to modify vendor directly, but I needed fast resolution of my problem and I wouldn't resolve something that was normally not my problem. 

As you said, I don't think it's related to deprecated SecurityContext service because that was just an exemple. In fact, I have several errors like that, and all are caused by deprecated services. I have many packages and all work fine. I just don't understand why those errors are only raised in this bundle.
