### ISSUE TITLE
Explaine the " $defaultOptions"

### ISSUE THREAD

**Issue by xorgxx** [tasmanianfox/MpdfPortBundle#34]
Hi i try to use your bundle but i have trouble with this : 

TFox\MpdfPortBundle\Service\MpdfService 

```
    public function generatePdf($html, array $argOptions = array())
    {
        //Calculate arguments
        $defaultOptions = array(
            'constructorArgs'      => array(),<---- here i suppose that we can use all think from \Mpdf\Mpdf library
            'writeHtmlMode'        => null,   <----- what does this represent
            'writeHtmlInitialise'  => null,   <----- what does this represent | header thml ?
            'writeHtmlClose'       => null,   <----- what does this represent | Body html ?
            'outputFilename'       => '',
            'outputDest'           => 'S',
            'mpdf'                 => null    <---- here i suppose that we can use all think from \Mpdf\Mpdf library
        );    
```
Thank for helping

**Comment by tasmanianfox** [comment]
Sorry for a very late response, the module is quite abandoned by me and I don't recommend to use it. I really have no idea what do these ```writeHtmlMode```, ```writeHtmlInitialise```, ```writeHtmlClose``` arguments. Basically, they are passed to WriteHTML function in mPDF, but I don't remember what they exactly mean. ```mpdf``` is an optional argument which is instance of original mPDF class. If it is passed, the mPdfBundle uses this instance instead of initialization of new one.
